alter table TRAMSERVERCUBA_WORK_TEAM add constraint FK_TRAMSERVERCUBA_WORK_TEAM_DEPO foreign key (DEPO_ID) references TRAMSERVERCUBA_DEPO(ID);
create unique index IDX_TRAMSERVERCUBA_WORK_TEAM_UK_NAME on TRAMSERVERCUBA_WORK_TEAM (NAME) where DELETE_TS is null ;
create index IDX_TRAMSERVERCUBA_WORK_TEAM_DEPO on TRAMSERVERCUBA_WORK_TEAM (DEPO_ID);
