create unique index IDX_TRAMSERVERCUBA_REGIONAL_DEPARTMENT_UK_REGION on TRAMSERVERCUBA_REGIONAL_DEPARTMENT (REGION) where DELETE_TS is null ;
create unique index IDX_TRAMSERVERCUBA_REGIONAL_DEPARTMENT_UK_NAME on TRAMSERVERCUBA_REGIONAL_DEPARTMENT (NAME) where DELETE_TS is null ;
