alter table TRAMSERVERCUBA_EMPLOYEE add constraint FK_TRAMSERVERCUBA_EMPLOYEE_WORK_TEAM foreign key (WORK_TEAM_ID) references TRAMSERVERCUBA_WORK_TEAM(ID);
alter table TRAMSERVERCUBA_EMPLOYEE add constraint FK_TRAMSERVERCUBA_EMPLOYEE_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_TRAMSERVERCUBA_EMPLOYEE_UK_NUMBER_ on TRAMSERVERCUBA_EMPLOYEE (NUMBER_) where DELETE_TS is null ;
create index IDX_TRAMSERVERCUBA_EMPLOYEE_WORK_TEAM on TRAMSERVERCUBA_EMPLOYEE (WORK_TEAM_ID);
create index IDX_TRAMSERVERCUBA_EMPLOYEE_USER on TRAMSERVERCUBA_EMPLOYEE (USER_ID);
