alter table TRAMSERVERCUBA_MAINTENANCE_WORK_TEMPLATE add column WORK_CLASS integer ^
update TRAMSERVERCUBA_MAINTENANCE_WORK_TEMPLATE set WORK_CLASS = 0 where WORK_CLASS is null ;
alter table TRAMSERVERCUBA_MAINTENANCE_WORK_TEMPLATE alter column WORK_CLASS set not null ;
