alter table TRAMSERVERCUBA_DEPO add constraint FK_TRAMSERVERCUBA_DEPO_REGIONAL_DEPARTMENT foreign key (REGIONAL_DEPARTMENT_ID) references TRAMSERVERCUBA_REGIONAL_DEPARTMENT(ID);
create unique index IDX_TRAMSERVERCUBA_DEPO_UK_NAME on TRAMSERVERCUBA_DEPO (NAME) where DELETE_TS is null ;
create unique index IDX_TRAMSERVERCUBA_DEPO_UK_CODE on TRAMSERVERCUBA_DEPO (CODE) where DELETE_TS is null ;
create index IDX_TRAMSERVERCUBA_DEPO_REGIONAL_DEPARTMENT on TRAMSERVERCUBA_DEPO (REGIONAL_DEPARTMENT_ID);
