-- alter table TRAMSERVERCUBA_AGGREGATE_ITEM_CHANGE add column TRANSPORT_ITEM_EQUIPMENT_ID uuid ^
-- update TRAMSERVERCUBA_AGGREGATE_ITEM_CHANGE set TRANSPORT_ITEM_EQUIPMENT_ID = <default_value> ;
-- alter table TRAMSERVERCUBA_AGGREGATE_ITEM_CHANGE alter column TRANSPORT_ITEM_EQUIPMENT_ID set not null ;
alter table TRAMSERVERCUBA_AGGREGATE_ITEM_CHANGE add column TRANSPORT_ITEM_EQUIPMENT_ID uuid not null ;
