alter table TRAMSERVERCUBA_EMPLOYEE add constraint FK_TRAMSERVERCUBA_EMPLOYEE_ON_WORK_TEAM foreign key (WORK_TEAM_ID) references TRAMSERVERCUBA_WORK_TEAM(ID);
alter table TRAMSERVERCUBA_EMPLOYEE add constraint FK_TRAMSERVERCUBA_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create unique index IDX_TRAMSERVERCUBA_EMPLOYEE_UNIQ_NUMBER_ on TRAMSERVERCUBA_EMPLOYEE (NUMBER_);
create index IDX_TRAMSERVERCUBA_EMPLOYEE_ON_WORK_TEAM on TRAMSERVERCUBA_EMPLOYEE (WORK_TEAM_ID);
create index IDX_TRAMSERVERCUBA_EMPLOYEE_ON_USER on TRAMSERVERCUBA_EMPLOYEE (USER_ID);
