alter table TRAMSERVERCUBA_WORK_TEAM add constraint FK_TRAMSERVERCUBA_WORK_TEAM_ON_DEPO foreign key (DEPO_ID) references TRAMSERVERCUBA_DEPO(ID);
create unique index IDX_TRAMSERVERCUBA_WORK_TEAM_UNIQ_NAME on TRAMSERVERCUBA_WORK_TEAM (NAME);
create index IDX_TRAMSERVERCUBA_WORK_TEAM_ON_DEPO on TRAMSERVERCUBA_WORK_TEAM (DEPO_ID);
